name: Build and test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        toolchain:
          - 1.61 # MSRV
          - 1.91
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: ~/.rustup
          key: rustup-${{ runner.os }}-${{ matrix.toolchain }}
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ matrix.toolchain }}

      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --locked --verbose
      - run: cargo clippy --locked -- --deny warnings
      - run: cargo clippy --locked --tests -- --deny warnings
      - run: cargo test --locked
      - run: cargo test --locked --features fastfloat
      - run: cargo test --locked --tests --no-default-features
      - run: cargo test --locked --tests --no-default-features --features fastfloat

# vim: ts=2 sw=2 expandtab
