name: Build and test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  server_and_client:
    name: Server and client
    strategy:
      matrix:
        toolchain:
          - 1.61 # MSRV
          - 1.84
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --locked --verbose
      - run: cargo clippy --locked -- --deny warnings
      - run: cargo clippy --locked --tests -- --deny warnings
      - run: cargo test --locked

# vim: ts=2 sw=2 expandtab
